---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

<style>
body {
text-align: justify; font-size:12pt}
</style>

## Deyme au fil des rues
### De l'Histoire aux histoires d'un petit village du Lauragais
#### Christian Balland

En sortant de Toulouse par la route de Narbonne, quelques minutes suffisent pour atteindre Deyme, village posé sur un plateau entouré de vallons. À ses pieds, la plaine lauragaise déroule un Canal du Midi paisible et ombragé, le lit de l’Hers mort, tantôt paradis des pêcheurs, tantôt synonyme de calamiteuses inondations, la Route Nationale 113, qui s’est substituée au Chemin français, et, depuis peu, comme tracée à la règle par un écolier méthodique, l’Autoroute des deux mers. 

Aux archives municipales, les documents assoupis tracent d’un murmure nostalgique les limites du “consulat”: “Belberaud d’Aquilon, Donneville du levant, Montbrun du Midi, Pompertuzat du couchant”…

Et toutes ces vieilles pages sentent bon les foins et le blé courbés par le Cers et l’Autan. Un auteur local notait en 1885 : “Les gens étrangers au pays se récrient souvent et avec juste raison de la violence du vent. Les tempéraments nerveux souffrent cruellement de migraines quand il souffle. Quand aux gens du pays, ils sont l’image de la santé, et quoique ne faisant point usages de mets très substantiels ils arrivent fréquemment à un âge avancé. Il y a un certain nombre de vieillards qui ont dépassé la quatre-vingtième année. Cela indique que l’air y est d’une salubrité remarquable.”

En ce temps là, les occasions de se rassembler ne manquaient pas. Pour le travail d’abord. Il y avait les moissons, les vendanges, l’écrêtage du maïs, les foins à rentrer et bien d’autres tâches “bronzantes”. Les journaliers apportaient leur aide dans une ambiance conviviale et partageaint le repas des employeurs. Le traditionnel bouquet de moisson, énorme gerbe décorée de feuillage et de fleurs des champs ou tressé en forme de croix, confectionné par les ouvriers à la fin des battages, était offert au patron ou à son épouse. En retour ils recevaient un pichet de vin ou de café et se voyaient conviés à un plantureux repas. Il en était de même pour les vendanges qui n’auraient pas été complètes sans se “moustouser”.

La “castagnado” bien “mouillée” de vin nouveau était un autre prétexte, ou la tuaille, où il ne faisait pas bon être cochon, et encore la fête du village et celles de fin d’année, où il ne faisait pas meilleur être un chapon ou une oie grasse! Combien chères aux paysans étaient les veillées hivernales. Bien couverts, les hommes, les femmes et les enfants affrontaient le froid et la neige pour se retrouver entre voisins, autant dire en famille, la grande famille des “travailleurs de terre”! Les coutumes et les traditions se perpétuaient dans une douce ambiance autour de crèpes ou de beignets devant les tisons pétillants. Un petit alcool était rarement refusé. Ne pas offenser le fabricant de cette “gnôle maison” revigorante était la clef des bonnes relations, surtout après une soupe au fromage ou encore après un bon cassoulet mitônné dans l’irremplaçable marmite en terre! Et chacun à sa manière racontait une histoire. Le cabaretier contait celles entendues dans son café où les clients, privés de labourage les jours de pluie, se réunissaient venus des fermes environnantes ou des communes voisines. Les amis de passage, friands de ces causeries célèbres à faire pâlir de jalousie madame Récamier, illustre inconnue comparée à notre conteur, ajoutaient aux galéjades qui n’étaient pas admises mais recommandées. Gervasy, entendez Gervais, le jardinier, livrait les secrets de l’école, de l’église ou des registres paroissiaux et citait avec une mémoire éblouissante dates, noms, lieux et événements qui avaient fait l’Histoire deymoise. Quel délice ! Un instituteur persistait à convertir les plus âgés au système métrique: « Finies les vieilles mesures… plus de boissel, de punière et d‘arpent. » Et pour faire oublier son intervention accueillie muettement, il tendait son verre en ajoutant: « Je vais vous le dire  en patois, vous comprendrez mieux!…«  La salle s’esclaffait. Quelques générations plus tard, rien n’avait changé. Le fils du forgeron parlait du labeur de son père et décrivait les outils de battage et leur fonctionnement, une parente du docteur le faisait revivre en quelques mots et le petit-fils du dernier meunier, maître-verrier de profession, décrivait le vitrail qui lui avait valu un grand prix et nous parlait de son grand-père. Parfois, dans cette société capable de rester attablée pendant des heures, il se trouvait autant de conteurs que de convives.

Les plus petits s’endormaient sur les genoux des grands-mères, s’ensuivaient des récits plus colorés destinés aux frères et soeurs ainés. Et l’on écoutait, serrés les uns contre les autres, se demandant parfois si les fleuves imaginaires ne prenaient pas leur source dans le monde réel. Venaient enfin les épisodes macabres. À ce moment, après un dernier « canard, » les adultes, installés à califourchon sur une chaise et les bras croisés appuyés au dossier, faisaient enfin silence. Un « Attendez-nous!… », partait de la cuisine. C’était une des mères de corvée. Parce que les mères, après la journée de travail et s’être occupées de leur progéniture, débarrassaient la table et s’apprêtaient à « vaisseler »! Heureusement, la mamée classait l’affaire: – Laissatz dròllas, la faretz doman, avètz le temps… vènetz escotar!… Assises près de leur époux, elles appuyaient leur tête sur les rudes épaules et, comme leurs pitchous, s’apprêtaient à sursauter. Les adolescents réunis en essaim approchaient curieux aux premiers Brrr!… Bouh!… Moun diou!… Le ronron du papé navigant sur la vague de sa canne, pourtant fermement tenue à deux mains, interrompait l’intrigue. Réveillé par les rires, il entendait à peine l’assemblée compter: « Une, deux… » À trois, l’air heureux, il repartait en mer! Lorsque les paupières se faisaient lourdes, ajoutant le rêve aux récits plus enflammés que les bûches dans l’âtre, il était temps de rentrer… à regret; Mais pour ma part, je retrouvais dans le cercle familial le complément de ces rencontres enrichissantes.

Un bel appartement, modèle de calme et de discrétion a succédé à la vivante forge. Dans le garage attenant, les socs de charrues et de brabants, les sacs de « coucarils » et les roues de charrettes en attente de « châtrage » ont fait place à l’indispensable voiture aux chevaux sans âme.

Les jeunes auditeurs attentifs des soirées feutrées ont aujourd’hui l’âge des conteurs d’antan. Ils froncent les sourcils au démarrage puant des encombrants véhicules diésel garés en désordre, et, le temps d’un soupir, revivent les odeurs de corne brûléee venues du « travail » où s’agite un boeuf en cours de ferrage. À peine couverts par la frappe du « ferratier » sur la bigorne, jaillissent les éclats de voix rehaussés de jurons imagés du forgeron.

En passant devant l’école, les cris des joueurs de balle au camp résonnent encore et, l’imagination aidant, des groupes semblent se former: les fin d’études dissertent près de la pompe, les cours moyens et préparatoires envahissent le potager, et, plus en couleurs et dentelles, un parterre féminin tient salon sous le marronnier planté pour l’inauguration. Derrière les murs sacrés, l’abbé célèbre une messe en latin et jette un oeil de reproche aux enfants de choeur distraits par des aboiements et de longs miaulements montés du jardin presbytéral…

 

Alors, comme jadis, du feu de cheminée ranimé, s’enfuient éperdues des milliers d’escarbilles chargées d’histoires qui, au désespoir d’atteindre les étoiles, savourent dans l’air frais le bonheur d’un salut éphémère et retombent en souvenirs…