---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

<style>
body {
text-align: justify; font-size:12pt}
</style>

<br>  


## Communiqués de guerre 1914-1918  

#### Christian BALLAND 

<br>

---  
 
### 1914



**31 juillet 22h15 –**Toulouse – Ordre du Ministère de l’Intérieur :  
Aviser discrètement les propriétaires d’animaux et de voitures de réquisition dès que l’ordre en serait donné. Veillez à éviter le cas échéant tout encombrement et tout désordre. Expédiez télégraphiquement et téléphoniquement aux communes ayant un bureau postal, à la distribution du 1er août aux autres communes.

**1er août 16h30 –** Extrême urgence – Circulaire recommandée :  
Ordre de mobilisation générale – Le premier jour de mobilisation générale est le dimanche 2 août.

**1er août 19h30 –** Villefranche de Lauragais – Sous-Préfet à Maires :  
Prière de faire connaitre télégraphiquement le nombre total des machines à battre appartenant à des entrepreneurs de votre commune et dans ces nombres combien fonctionnent actuellement dans votre commune ou ailleurs et combien sont arrêtées faute de mécaniciens.

**9 août –** Villefranche de Lauragais – Sous Préfet Villefranche à Maires arrondissement :  
Les français vainqueurs à Altkirch envahissent l’Alsace et occupent Mulhouse.

**10 août 10h50 –** Villefranche de Lauragais – Sous Préfet Villefranche à Maires arrondissement :  
Prière de faire connaître par dépêche s’il existe dans votre commune des affiches qui vous paraîtraient suspectes.

**13 août 12h25 –** Villefranche – Préfet à Maires :  
Depuis hostilités nombreux cavaliers allemands en patrouille ont résisté énergiquement près de Dorlemont en Belgique Les belges ont résisté à sérieuses attaques allemandes. Enfermé des autrichiens ont été partout repoussés ils n’ont pu pénétrer en Serbie

**14 août 12h50 –** Toulouse – Préfet à Maires :  
France et Angleterre ont déclaré la guerre à l’Autriche. Belges continuent repousser victorieusement des attaques allemandes. Deux bataillons français ont été repoussés par forces importantes allemandes. Partout ailleurs les engagements de front ont tourné à l’avantage des troupes françaises qui ont fait des prisonniers.

**15 août –** Toulouse – Préfet à Maires :  
Quelques engagements sur les fronts des troupes à Chambray à (…) les allemands ont été repoussés par nos troupes. De nombreuses patrouilles allemandes poursuivies par des français se réfugient en Suisse. Deux aviateurs allemands atteints par les tirs de nos soldats sont tombés et ont été faits prisonniers. Le général anglais French a rendu visite à Paris au Gouvernement et au Président de la République. Avant de rejoindre l’armée anglaise dans le nord de la France d’importantes forces françaises entrent en Belgique par Charleroy.

**15 août 11h –** Préfet aux Maires de Haute-Garonne :  
À notre aile gauche nos troupes en progression continue, l’ennemi se replie vers la Marne.les troupes anglaises coopèrent à cette action. Un bataillon d’Infanterie allemande avec mitrailleuse a été fait prisonnier. L’ennemi a marqué un mouvement de recul entre Fère-Champenoise et Vitry-le-François où a eu lie violent combat. À notre droite les allemands ont été repoussés au nord de Champereux. Les victoires russes continuent en Galicie.

**16 août 12h22 –** Préfet à Maires :  
Plusieurs engagements ont eu lieu entre les russes et les troupes austro-allemandes qui partout ont été repoussées. Le Tsar a fait connaître à la Pologne allemande autrichienne et russe son intention de lui restituer son intégrité territoriale. Les forts de Liège tiennent toujours. En Alsace une affaire importante a été engagée en troupes françaises contre un corps bavarois qui s’est retiré laissant morts, blessés et prisonniers. En Haute Alsace, Thann a été repris par nos troupes qui se sont emparées de drapeaux allemands. Le gouvernement fait appel à la sagesse et à la clairvoyance des populations aux nouvelles bonnes ou mauvaises et qui parviendront de différents points. Pendant plusieurs jours, une semaine peut-être, présentera de nombreuses (…) avant qu’un résultat ne soit obtenu. Le pays a déjà pu se rendre compte que le plan allemand, que l’attaque brusque avait échoué tant sur la Belgique que sur Nancy. Pendant ce temps notre mobilisation et notre concentration a pu s’opérer entièrement. Le pays suivra avec sang-froid les phases de ce choc de 400 kilomètres d’étendue avec confiance les résultats décisifs.

**17 août –** Toulouse – Préfet à Maires :  
Opération frontière de l’Est à Balmont Ciray une division française a attaqué vendredi soir ennemi fortement retranché. Samedi nos troupes ont continué vigoureusement offensive. Un corps d’armée bavarois débordé par notre colonie a du se replier vers Sarrebourg. Nos troupes ont franchi la frontière sur ce point. Au sud les troupes françaises se sont emparées du massif du Domon, ont enlevé Sainte-Marie-aux-Mines progressivement. Dans la région Saint Blaise, dans la vallée Schirmeck, plus 1500 prisonniers ont été pris ainsi que 19 camions automobiles. Notre situation est excellente en Haute Alsace . Succès à Dinant en Belgique les troupes françaises ont repoussé une division de la garde allemande, plusieurs divisions de cavalerie, d’infanterie et d’artillerie. Ces attaques menées avec beaucoup de vigueur ont obligé les troupes allemandes à repasser la Meuse en désordre où en plus de leur perte ils ont eu de nombreux noyés. En Russie, les troupes russes ont commencé à franchir la frontière repoussant devant elles les troupes allemandes et autrichiennes. Le Japon a adressé à l’Allemagne un ultimatum fixant un délai d’un mois pour évacuation des possessions allemandes en Extrême-Orient et imposant le désarmement des navires.

**18 août 11h30 –** Toulouse :  
La progression de nos troupes continue à se développer sur le front Alsace-Lorraine jusqu’au sud de Metz. Les prises de guerre sont nombreuses, canons, caissons, convoi de camions automobile, effets d’équipements, matériels. Les premiers drapeaux allemands ont été pris en Alsace par le 10ème régiment de Chasseurs à pied. Il a été apporté au Cabinet du Ministre de la Guerre à Paris. La flotte française a coulé devant le Montenegro un croiseur autrichien. Un aviateur allemand a été abattu près de Givet.

**19 août 10h55–** Toulouse – Préfet à Maires :  
Le Général Joffre Commandant en chef des armées a confirmé par télégramme au Ministre de la Guerre la progression continue de nos troupes en Alsace, un convoi allemand a été pris dans la région près de Dinant, le Maire de Badonviller a été fait Chevalier de la Légion d’Honneur en récompense de la présence d’esprit et du courage dont il a fait preuve devant l’ennemi.

**Août (Sans date) –** Toulouse – Préfet à Maires :  
La bataille a continué sur la front de l’Oise et de la Woëvre pendant la journée du 17 sans modification importante de la situation sur aucun point. À notre aile gauche sur les hauteurs au nord de l’Aisne, nous avons légèrement progressé sur certains points. Trois retours offensifs tentés par les Allemands contre l’armée anglaise ont échoué. De Craonne à Reims,nous avons nous-mêmes repoussé de très violentes attaques exécutées la nuit. L’ennemi a en vain essayé de prendre l’offensive contre Reims. Au centre de Reims à l’Argonne et à Woëvre situation inchangée. À notre aile droite Lorraine et Vosges, l’ennemi occupe des positions organisées défensivement dans le voisinage de la frontière.

**20 août 12h15 –** Toulouse – Préfet à Maires :  
En Haute-Alsace, nos troupes avancent lentement mais régulièrement malgré l’organisation fortifiée des allemands. Elles occupent Château-Salins, Dieuze et débouchent sur la vallée de la Seille. Des forces allemandes très importantes passent la Meuse entre Liège et Namur. À Florenville, frontière belge, une rencontre de cavalerie a tourné à notre avantage.

**21 août –** Toulouse – Préfet à Maires:  
En Haute Alsace, les troupes françaises ont occupé Guebwiller et ont repris Mulhouse à la baïonnette. En Lorraine ont rencontré d’importantes forces allemandes. Ils se sont repliés sur le gros de nos troupes solidement établi sur la Seille et le canal de la Marne au Rhin. En Belgique, la cavalerie allemande a atteint Bruxelles. L’offensive russe est générale contre l’Allemagne et l’Autriche. 

**22 août 14h25 –** Préfet à Maires :  
En Lorraine nos troupes ont du se replier. rudement devant des forces supérieures devant des forces supérieures. Elles se sont solidement appuyée au Donon d’une part, et aux ouvrages avancés de Nancy d’autre part. En Alsace le général Pau a brillamment conduit l’affaire de Mulhouse. Les allemands ont eu à repasser le Rhin en désordre avec des pertes considérables.

**22 août –** Préfet à Maires :  
À notre aile gauche sur la rive droite de l’Oise, nous avons progressé jusqu’à la hauteur de Lassigny. À l’ouest de Noyon, à l’est de l’Oise et au nord de l’Aisne, les allemands ont profité d’une recrudescence d’activité. Des combats violents allant jusqu’à la charge à la baïonnette se sont livrés dans la région de Craonne, l’ennemi a été partout repoussé avec des pertes considérables. Autour de Reims l’ennemi n’a tenté aucune attaque d’Infanterie et s’est borné à canonner notre front avec de grosses pièces. Au centre en Champagne et sur le revers occidental de l’Argonne, outre Souain, nous avons pris Mesnil-les-Hurins et Massiges en Woëvre. L’ennemi tient toujours dans la région de Thiancourt et a canonné Hattontchâtel. À l’aile droite Lorraine et Vosges rien de nouveau. Les allemands se fortifient sur la cote de Delme et au sud de Château Salins.

**23 août –** Villefranche Lauragais – Sous-Préfet à Maires :  
Vous prie me faire parvenir aussitôt que vous les recevez les demandes de renseignement qui vous seront adressées par la famille pour obtenir des nouvelles de leurs parents actuellement sous les drapeaux. Se conformer strictement pour demande en affiche qui vous a été (vitament) envoyée.

**23 août –** Toulouse :  
En Belgique la situation est toujours la même. L’armée belge est prête dans le Comps d’Anvers. En Lorraine l’offensive allemande a été arrêtée hier au nord de Nancy. Au cours des dernières journées les pertes ont été sensibles des deux cotés.

**25 août –** Toulouse – Préfet à Maires :  
La bataille générale est complètement engagée sur tout le front de Mons au Luxembourg.Nos armées sont mises en marche 22 août et ont commencé par prendre l’offensive, l’une partant sur Neufchâteau l’autre sur les Ardennes, la 3ème se dirigeant entre Sambre et Meuse. L’armée anglaise a opposé une admirable résistance au choc des allemands. Nos troupes ont été contre-attaquées avec vigueur après avoir subi des pertes sensibles et et après en avoir infligées de graves aux allemands. Elles ont pris la défensive ainsi que les troupes anglaises. Elles se sont établies sur notre ligne de couverture où elles reprendront l’offensive lorsque le général en chef le jugera à propos. Les allemands eux-mêmes sont éprouvés et ont arrêté leur contre-attaque pour s’établir sur des nouvelles positions. En Lorraine le général Pau commande en chef. Nos troupes ont contre-attaqué les allemands au Nord de Nancy et ont infligé de grosses pertes. Quelques régiments de cavalerie allemande ont été vus à Tourcoing. Un journal de Paris aurait dit qu’une partie du 15ème Corps d’Armée avait lâché prise devant l’ennemi. Le Gouvernement a infligé un blâme à ce journal. En réalité il s’est produit quelques défaillances individuelles qui ont été sévèrement réprimandées.

**26 août –** Toulouse – Préfet à Maires :  
En Belgique nos troupes se sont établies sur nos lignes de couvertures. L’armée anglaise elle, occupe une ligne passant près de Givet elles se trouve à droite au débouché de la vallée des Ardennes. Nos troupes coloniales se sont rencontrées avant-hier avec la Garde Impériale prussienne qui a été détournée après une lutte acharnée. Au cours de cet engagement l’oncle de l’Empereur a été tué. À l’heure actuelle où la partie importante se joue dans le nord, le théâtre d’opération d’Alsace devient secondaire, aussi le général en chef a-t-il appelé sur la frontière belge une partie des troupes qui occupaient cette région pour aider à cette conversion. Mulhouse a été évacuée. En Lorraine nos troupes ont pris l’offensive et sont engagées dans un combat qui dure encore. Les russes continuent leur marche en avant, toute la Prusse Orientale est envahie.

**28 août –** Toulouse – Préfet à Maires :  
Dans les Vosges nos troupes ont repris l’offensive et refoulé les forces allemandes qui hier avaient commencé le bombardement de Saint-Dié. À l’extrême frontière, la très vieille forteresse de Longwy depuis le 3 août a du capituler hier après une héroïque résistance. Le lieutenant Larcher gouverneur de la place a été fait Chevalier de la Légion d’Honneur. Entre les Vosges et Nancy, notre offensive n’a pas cessé depuis cinq jours. Les pertes allemandes sont considérables, elles s’élèvent à 2500 morts sur un parcours de 3 kilomètres. Sur la Meuse nos troupes ont repoussé avec une extrême vigueur plusieurs attaques allemandes. Un drapeau a été pris. Les troupes anglaises du nord se sont reporté en arrière après une héroïque résistance contre un ennemi supérieur en nombre. À leur droite nos armées ont maintenu leur position. L’armée d’Anvers poursuit l’offensive.

**30 août –** Toulouse – Préfet à Maires :  
En Lorraine la progression de nos forces s’est accentuée, nous sommes maîtres de la montagne, notre droite avance, rien à signaler sur le front de la Meuse. Une violente action a eu lieu hier sans résultat décisif, l’attaque reprendra demain. À notre aile gauche une véritable attaque a été menée par quatre de nos corps d’armée. La droite des corps pressant l’offensive a repoussé sur Guise et à l’est une attaque conduite par le 10ème corps allemand et la garde qui ont subi des pertes considérables. La gauche a été moins heureuse, des forces allemandes progressent dans la région de l’Aisne.

**1er septembre –** Toulouse – Préfet à Maires :  
La situation dans l’ensemble est la même que ce matin après une accalmie. La bataille a repris dans les Vosges et en Lorraine. Sur la Meuse un régiment d’Infanterie qui avait tenté de passer la rivière a été presque anéanti. À notre gauche les forces de l’aile marchante nous oblige à céder du terrain.

**1er septembre 10h55 –** Toulouse – Préfet à Maires :  
Veuillez me faire connaitre télégraphiquement combien de réfugiés français de la région du nord consentiraient à recevoir les habitants de votre commune. La subsistance et l’entretien chez l’habitant, le sentiment de solidarité qui doit tenir tous les français me laisse espérer une réponse rapide et très favorable.

**1er septembre –** Toulouse – Préfet à Maires :  
La situation générale ne s’est modifiée que sur nos ailes. À notre gauche les allemands ont gagné quelque terrain. Dans le centre pas de modifications sensibles, on ne s’est pas battu. En Lorraine nous avons remporté de nouveaux avantages.

**2 septembre –** Toulouse – Préfet à Maires :  
À notre aile gauche par suite de la continuation de du mouvement enveloppant et dans le but de ne pas affecter une action décisive qui aurait pu être engagée dans de mauvaises conditions nos troupes se sont repliées. Partie vers le Sud-Ouest, l’action engagée dans la région de Rethel a permis à nos forces d’arrêter momentanément l’ennemi au centre et à notre droite. Lorraine et Vosges situation sans changement. A été organisée une escadrille d’Aéroplanes garnies de mitrailleuses pour faire la chasse aux aéroplanes qui survolent Paris.

**3 septembre 14h12 –** Toulouse – Préfet à Maires :  
Aile gauche dans la journée du premier septembre: un corps de cavalerie allemande dans marche dans la forêt de Compiègne a eu lieu un combat avec les anglais qui lui ont pris 10 canons. Un autre corps de cavalerie allemande a poussé jusqu’à la ligne Soissons-Anizy le Château. Région Rethel et de la Meuse l’ennemi n’a montré aucune activité. En Lorraine, nous avons contribué à progresser sur la rive droite du Sânon. Au sud, la situation n’a pas changé. En Haute Alsace les allemands semblent n’avoir laissé devant Belfort qu’un rideau de troupe. Dans la région du nord, on ne signale pas d’ennemis à Lille, Arras, Doouai et Béthune. Cent fractions appartenant à plusieurs corps d’armée allemande sont mises en mouvement vers l’est rentrant en Allemagne.

**6 septembre –** Toulouse – Préfet à Maires :  
À notre aile gauche la situation respective des armées françaises et allemandes n’a subi aucune modification inteéressante, la manoeuvre débordante de l’ennemi définitivement conjurée sur notre centre et à droite.Lorraine et Vosges situation rien changé. À Parisdont l’ennemi reste éloigné, les travaux de défense se font avec activité. À Maubeuge, le bombardement a continué avec une etreinte violente; la place résiste. La déclaration suivante a été faite ce matin à Londres: « Les soussignés du Gouvernement autorisés par leur Gouvernement respectif font la déclaration suivante de s’engager actuellement, de ne plus se séparer au cours de la présente guerre. Les trois gouvernements conviennent lorsqu’il y aura lieu de discuter les termes de la paix qu’aucune des puissances alliées ne pourrait poser des conditions de paix sans chacune des autres alliées » Ont signé: Edward Grey, Ministre des Affaires Étrangères, Paul Cambon, ambassadeur de France à Londres et le comte Benckerdorff, ambassadeur de Russie à Londres.

**6 septembre –** Toulouse – Préfet à Maires :  
À notre gauche l’ennemi aurait négligé tout pour poursuivre sa tentative de mouvement. Il atteint La Ferté sous Jouarre dépasse Reims et descend le long à l’ouest de L’Argonne. Cette manoeuvre n’a pas pu atteindre son but tant aujourd’hui que les jours précédents. Lorraine et Vosges on se bat toujours pied à pied avec des alternatives diverses. Maubeuge violemment bombardé resiste avec vigueur. Les nouvelles russes annoncent une victoire russe à Lamberg après une bataille qui a duré sept jours. Les autrichiens sont hors de combat, ont abandonné un grand nombre de canons de campagne, une quantité considérable de fusils et de mitrailleuses. Les russes ont fait des milliers de prisonniers. Un nouveau télégramme annonce que Lamberg a été pris par les russes.

**6 septembre 10h30 –** Toulouse – Préfet à Maires :  
Nos troupes sont rentrées dans Amiens. À notre aile gauche nos armées sont en contact avec l’ennemi dans la Forêt de l’Aigle. Au nord de l’Aisne à l’ouest et au nord de Reims notre centre continue sa marche en avant entre l’Argonne et la Meuse. À notre aile droite les allemands se replient sur Étain, Metz, Delme et Château-Salins. En Belgique l’armée belge continue à rayonner autour d’Anvers faisant subir à l’ennemi des pertes considérables.

**7 septembre –** Toulouse – Préfet à Maires :  
À notre aile gauche nos armées ont repris combat dans de bonnes conditions. L’aile droite ennemis sur les rives du Grand-Maurin, sur notre centre et à notre droite Lorraine et Vosges ont continué à se battre, aucun changement hier. L’engagement s’est produit hier entre des éléments de défenses avancés de Paris et le flanc (…) de l’armée d’aile droite allemande a plus d’ampleur. Nous nous sommes avancés jusqu’à l’Ourq sans rencontrer une grande résistance. La situation des armées allieès parait bonne dans son ensemble. Maubeubeuge continue à résister héroïquement. Le drapeau du 28ème d’Infanterie allemande dans un récent combat et le colonel fait prisonnier. Le 137ème régiment d’Infanterie française qui a accompli le brillant fait d’armes a eu son drapeau décoré de la Légion d’Honneur.

**11 septembre 10h20 –** Toulouse – Préfet à Maires Haute-Garonne :  
Aile gauche les troupes anglo-françaises ont franchi la Marne entre La Ferté-sous-Jouarre, Senlis et Chäteau-Thierry. Au cours de cette agression l’armée britannique a fait de nombreux prisonniers et pris des mitrailleuses. Entre Château-Thierry et Vitry-le-François, la garde prussienne a été rejetée au nord des Marais de Saint-Gond. L’action continue avec une grande violence dans la région comprise entre Le Camp de Mailly et Vitry-le-François. Au centre et aile droite situation stationnaire sur l’Ornain et l’Argonne où les deux adversaires se maintiennent dans leurs positions. Du côté de Nancy l’ennemi a légèrement progressé sur la route de Château-Salins. Par contre nous avons gagné du terrain sur le fond de Champennoux où les pertes sont considérables de part et d’autre. L’état moral et sanitaire de nos troupes reste excellent. Aucune confirmation n’est parvenue jusqu’à présent des nouvelles données par la presse allemande de la chute de Maubeuge.

**21 septembre 11h50 –** Toulouse – Préfet à Maires :  
À notre aile gauche sur la rive droite de l’Oise nous avons réalisé de légers progrès. Au nord de l’Aisne, à l’avant de Soissons, nos troupes violemment attaquées par des forces supérieurs ont cédé quelque terain qu’elles ont presque aussitôt reconquis. Au nord de Reims nous avons repoussé toutes les attaques ennemies cependant très vigoureusement menées. Au centre et à l’est de Reims nos attaques ont fait de nombreux progrès. Les allemands se sont acharné à bombarder la cathédrale de Reims qui est tout en flammes. Entre Reims et l’Argonne nous avons enlevé le village de Souain, fait un millier de prisonniers. Sur le revers occidental de l’Argonne nos progrès sont confirmés. En Lorraine l’ennemi s’est reculé au-delà de notre frontière évacuant en particulier la région d’Avricourt. Ses tentatives défensives aux abords de Saint-Dié sont restées sans succès.

**23 septembre 10h30 –** Toulouse – Préfet à Maires :  
À notre aile droite sur la rive droite de l’Oise les allemands ont du céder du terain devant les attaques françaises. Entre l’Oise et l’Aisne situation inchangée l’ennemi n’a pas attaqué sérieusement se bornat hiersoir à une énorme canonnade. Au centre entre Reims et Souain, il a tenté une offensive qui a été repoussée tandis qu’entre Souain et l’Argonne nous avons fait quelques progrès. Entre l’Argonne et la Meuse, aucun changement. En Woëvre l’ennemi a fait un violent effort il a attaqué les Hauts de Meuse, sur le front très (…) aux Vigneulles-Haudricourt sans pouvoir prendre pied sur les hauteurs. À notre droite en Lorraine il a de nouveau franchi la frontière. Avec une serie de petites colonnes il a réoccupé Domèvre au sud de Blamont. Dans les journées des 20 et 21 nous avons pris 20 autos de ravitaillement avec tout leur personnel et de nombreux prisonniers appartennant notamment aux 4ème, 6ème, 7ème, 8ème, 9ème, 13ème, 14ème, 16ème corps allemands à la Land vorher bavarois et à des corps de réserve.

**27 septembre –** Toulouse – Préfet à Maires :  
Les allemands ont attaqué sur tout le front, partout ils ont été repoussés. Dans la région des Hauts de Meuse l’ennemi a pu franchir la Meuse à Saint-Mihiel où l’offensive prise par nos troupes l’a déjà en majeure partie rejeté dans la rivière. En Woëvre nous continuons à gagner du terrain.

**28 septembre –** Toulouse – Préfet à Maires :  
À notre aile gauche la bataille continue avec desprogrès sensibles sur un front très étendu entre l’Oise et la Somme. De l’Oise à Reims très violentes attaques allemandes sur plusieurs points, quelques unes menées jusqu’à la baïonnette et toutes repoussées. Les lignes de tranchées françaises et allemandes ne se trouvent en maints endroits qu’à quelques centaines de mètres les unes des autres. Au centre de Reims à Souain la garde prussienne a prononcé sans succès une vigoureuse offensive et a été réjetée dans la région de Berru et de Nogent-l’Abbesse. De Souain à l’Argonne l’ennemi a attaqué dans la matinée d’hier avec avantage entre la route de Sommepy à Châlons et la voie ferrée de Sainte-Ménehould à Vouziers. En fin de journée nos troupes ont regagné le terain perdu. Entre l’Argonne et la Meuse, l’ennemi n’a manifesté aucune activité. Sur les Hauts de Meuse rien de nouveau. Dans le sud de la Woëvre les allemands occupent un front qui passe par Saint Mihiel et le nord ouest de Pont-à-Mousson. Lorraine, Vosges, Alsace, aucune modification importante. Il se confirme que depuis la nuit du 25 au 26 jusqu’à la journée du 27 nuit et jour, les allemands n’ont céssé de renouveller sur tous les fronts des attaques d’une violence inouïe dans le but manifeste de rompre nos lignes avec un ensemble qui dénote des instructions du haut commandement de chercher la sécurité de la bataille. Non seulement ils n’y sont pas parvenus mais nous avons pris un drapeau des canons et fait de nombreux prisonniers. Le drapeau a été pris par le 24ème régiment d’Infanterie Coloniale que nos commandants d’armée signalent tant malgrè les fatigues de cette lutte l’entreprise est excellente ils ont eu du mam à les retenir dans leur désir d’aborder l’ennemi dans ses organisations défensives.

**5 octobre –** Toulouse – Préfet à Maires :  
À notre aile gauche nous avons repoussé toutes les attaques ennemies, nous avons repris l’offensive sur plusieurs points. La lutte bat son plein dans la région d’Arras. Nous avons progressé dans la région de Soissons où des tranchées ennemies ont été prises. Dans l’Argonne nous avons repoussé l’ennemi vers le nord. Dans la Woëvre méridionale nous progressons mais très lentement. À notre aile droite Lorraine et Vosges rien de nouveau.

**5 octobre –** Toulouse – Préfet à Maires :  
À notre aile gauche la bataille continue très violente et reste indécise, nous avons cédé du terrain sur certains points. Dans l’Argonne et sur le Haut de Meuse nous avons repoussé des attaques de jour et de nuit. En Russie, après une bataille qui a duré dix jours, l’armée allemande qui opérait entre la frontière de la Prusse Orientale et le Niémen a été battue sur toutes les lignes et effectué sa retraite en abandonnant un nombreux matériel. Le général Joffre et le Grand Duc Nicolas ont échangé des télégrammes de félicitation.

**8 octobre –** Toulouse – Préfet à Maires :  
À notre aile gauche la bataille continue avec une grande violence. Les attaques allemandes ont été repoussées. La cavalerie ennemie a été maintenue au nord de Lille où elle avait été refoulée entre Chaulnes et Roye. Le terrain prudemment cédé a été repris. Au centre nous avons avancé sur certains points. À l’aile droite l’ennemi qui avait tenté en Woëvre un nouvel effort pour arrêter nos troupes a été repoussé. En Russi les troupes russes continuent la poursuite allemande. Et ont franchi sur plusieurs points la frontière de Prusse Orientale.

**8 octobre –** Toulouse – Préfet à Maires :  
Veuillez mettre en garde familles des mobilisés qui seraient sollicitées par banques étrangères pour envoi argent destiné à prisonniers de guerre.

 
---  

 
### 1915

 

**21 mai –** Toulouse – Préfet à Maires :  
Allons recevoir très prochainement 2000 réfugiés français évacués d’Allemagne pour notre arrondissement. Prière me faire savoir immédiatement par télégramme combien vous pouvez en loger dans les locaux communaux ou privés actellement disponibles. La nourriture n’est pas à la charge des communes.

**22 mai –** Toulouse – Préfet à Maires :  
Nos troupes ont achevé en fin de journée le nettoyage des tranchées de la Blanche Voie. De très nombreux allemands ont été tués dans les boyaux de communication, les autres se sont rendus. On ne connait pas le chiffre exact. Pendant la nuit l’ennemi a plusieurs fois contre attaqué. Il a eté repoussé et a subi de grosses ertes. Tout l’éperon de la blanche voie est entre nos mains. Nous avons progressé au lieu sud-est de la Chapelle de Lorraine. Nous sommes à 100 mètres de la Corne (…) à Blette.

**25 mai –** Toulouse – Préfet à Maires :  
Nuit assez agitée entre la mer et Arras. En Belgique à la suite d’un bombardement violent une attaque allemande a tenté de déboucher entre la route de Lange Mare à Ypres. Elle a été arrêtée net au Nord d’Ablain. Les allemands ont attaqué deux fois. Ils ont été repoussés au nord de Neville. Ils ont prononcé quatre attaques et ont été arrêtés par le feu de notre artillerie. L’ennemi dans ses diverses tentatives qui ont abouti pur lui à des échecs complets a subi de grosses pertes. Sur le reste des fronts rien à signaler.

**26 mai 11h20 –** Toulouse – Préfet à Sous-Préfets et Maires département :  
À l’heure où l’Italie entre en lutte à nos cotés pour la défense du Droit et de la Liberté des peuples je vous invite à pavoiser en son honneur.

**26 mai 17h20 –** Toulouse – Préfet à Maires :  
Les échecs subis hier dans la région d’Angres au nord-ouest du massif de Notre-Dame de Lorette ont déterminé de sa part une réaction extrêmement violente. On s’est battu sérieusement dans la forêt pendant la nuit, nous avons conservé tous nos gains. Nos troupes ont fait preuve d’un courage et d’une tenacité magnifique. Les allemands ont contre-attaqué l’ouvrage conquis par nous au nord-ouest d’Angres. Et ont multiplié des efforts acharnés pour le reprendre. Malgré le bombardement exceptionnellement intense auquel nous avons été soumis nous avons gardé la totalité de nos nouvelles positions. Nous avons d’autre part en fin de journée occupé presque entièrement le (..on) de Duval que nous avons pris hier dans l’après-midi. Nous nous y maintenons sous un feu violent. Sur la crête au nord-est de Notre-Dame nous avons enlevé une tranchée ennemie aux abords de Souchez. Une lutte d’artillerie s’est engagée dans la région de Soissons et dans celle de Reims. Sur le reste du front rien n’a été signalé au cours de la journée du 25.Nous avions sur le front réussi une très grande activité et réussi plusieurs entreprises de bombardement. Ils ont lancé 203 projectiles dont 8 grosses bombes d’un poids de 10 kg et 14 obus de 155 d’un poids de 43 kg. Les explosions ont pu être constatées sur plusieurs points notament aux (…) d’aviation allemande de Hervilly ou en un hangar et un avion ont pris feu, à la réserve d’aviation allemande du Grand Priel nord-ouest de Saint-Quentin où un hangar a été écrasé , à la gare de Saint-Quentin dont le dépôt d’essence a été atteint. Au cours de la nuit précédente d’autres obus ont été lancés sur la gare de Douai. Un incendie a été constaté dans le voisinage de la gare de marchandise.

**27 mai –** Toulouse – Préfet à Maires :  
Les troupes belges onrt repoussé hier soir deux attaques allemandes au nord et au sud de Dixmude. La première a été refoulée par une contre attaque, la deuxième a été arrêtée par notre feu. Dans le secteur au nord d’Arras deux attaques se sont produites au sud-ouest de Souchez. Nous nous sommes emparés d’une tranchée du château de (Corlel?) en faisant des prisonniers dont l’officier. À l’est de Neuville-Saint-Vaast les allemands ont tenté une attaque qui a été briséepar notre artillerie. Sur divers points du front notamment près de Reims et dans les Vosges combats d’artillerie. Une de nos escadrilles composée de dix-huit avions portant chacune (…) kilos de projectiles a bombardé ce matin l’une des plus importantes fabriques de produits chimiques d’Allemagne. Les résultats constatés ont prouvé l’efficacité du bombardement. Plusieurs bâtiments ont été atteints, de nombreux incendies ont été allumés. Nos aviateurs sont restés plus de 6 heures en l’air et ont parcouru plus de 400 kilomètres. Cette expédition contre un important établissement militaire a servi de riposte aux aviateurs allemands sur Paris.

**28 mai 15h15 –** Toulouse – Préfet à Maires :  
Dans la région au nord d’Arras la nuit a été marquée par unelutte d’artillerie très violente. L’ennemi a particulièrement bombardé les positions du plateau de Lorette. Une attaque de nuit nous a permis de réaliser de nouveaux progrès à l’est de route Aix-Noulette-Souchez. Vers minuit une contre-attaque sur nos tranchées d’Ablain-Saint-Nazaire a été facilement repoussée. En Argonne dans la région de Fontaine Madame nous nous sommes emparés d’un élément de tranchées ennemies.

**31 mai –** Toulouse – Préfet à Maires :  
Rien de nouveau dans la nuit du 30 au 31 si ce n’est l’échec dans la région nord-est de Lorette. Une attaque allemande a été facilement repoussée nous avons fait 150 prisonniers dont 4 officiers au labyrinthe sud-est Neuville-Saint-Vaast.

**1er juin 15h15 –** Toulouse – Préfet à Maires :  
Dans la région au nord d’Arras de violents combats ont été livrés pendant la nuit à l’est de la route Aix-Noulette-Souchez. Nous avons pénétré dans un boquetteau où s’est engagé une lutte au corps à corps dans laquelle nous avons eu l’avantage. Sur le plateau à l’est de Notre-Dame de Lorette nous nous sommes emparés d’un ouvrage allemand. Un combat très violent s’est déroulé autour de la sucrerie de Souchez où nous avons fait une soixantaine de prisonniers. Dans les Vosges près de La Fontenelle nord de Saint-Dié au cours de la nuit du 30 au 31 mai une attaque allemande menée par deux compagnies a été repoussée avec de très lourdes pertes pour l’ennemi.

**2 juin 16h –** Toulouse – Préfet à Maires :   
Dans le secteur au nord d’Arras le combat a continué cette nuit dans le labyrinthe au sud-est de Neville. Nous avons conquis un groupe de maisons où nous nous sommes maintenus malgré plusieurs attaques. Dans les autres parties du secteur notament à Lorette combat d’artillerie. Sur le reste du front si ce n’est un bombardement deux fois répétées de Reims et particulièrement de la cathédrale.

**4 juin 16h –** Toulouse :  
À l’est de la sucrerie de Souchez nos troupes progressant dans le village de Souchez ont enlevé un cabaret que l’ennemi avait organisé. Fait une cinquantaine de prisonniers et pris trois mitrailleuses. Elles ont d’autre part réalisé d’autres progrès dans le labyrinthe.Sur la route du front combat d’artillerie.

**5 juin 16 h –** Toulouse – Préfet à Maires :  
L’ennemi a prononcé dans la nuit trois violentes contre-attaques contre la sucrerie de Souchez et nos tranchées au nord et au sud. Il a été repoussé et a subi de lourdes pertes surtout dans la première tentative. Nous restons maîtres de la totalité des positions conquises. Cette nuit également nous avons enlevé un poste allemand au nord-ouest du Cabaret Rouge un kilomètre sud de Souchez. L’activité de l’artillerie a été grande dans tout le secteur au nord d’Arras. Sur le reste du front rien de nouveau.

**7 juin –** Toulouse – Préfet à Maires :  
Dans le secteur au nord d’Arras la nuit a été marquée par un combat d’artillerie d’une extrême intensité notamment dans la région de Lorette, d’Alain, du Cabaret Rouge près Souchez, du labyrinthe et d’Écurie. L’ennemi a prononcé deux contre-attaques qui ont complètement échoué, l’une sur la sucrerie, de Souchez qui a été arrêtée par notre artillerie, l’autre dans la partie nord du labyrinthe qui a été refoulée par notre infanterie. De notre coté nous avons réalisé des progrès nouveaux. Nous avons en particulier gagné du terrain à un kilomètre est de la chapelle de Lorette et conquis dans le labyrinthe une centaine de mètres dans la prtie centrale de l’ouvrage. Le matin à 5 heurs nous avons attaqué près d’Hébuterne la position de l’ennemi près de la ferme Touvent. Nous avons enlevé sur un front de 1200 mètres deux lignes successives de tranchées, fait des prisonniers et pris des mitrailleuses. Au nord de l’Aisne près de Moulin-sous-Touvent la contre attaque signalée hier a été poursuivie toute la nuit. Nous avons par de combats très chauds maintenu nos gains et conservé sur un front de un kilomètre environ les deux lignes enlevées à l’ennemi. La tentative de bombardement de Verdun signalée avant hier ne s’est plus renouvelée. Sur le reste du front rien à signaler.

**9 juin –** Toulouse –  Préfet à Maires :  
Rien à ajouter au communiqué d’hier soir si ce n’est une progression sur 350 mètres du front aux lisières du Bois-le-Prêtre où nous avons enlevé 2 et sur certains points 3 lignes de tranchées allemandes et fait une cinquantaine de prisonniers.

**10 juin 10h10 –** Toulouse – Préfet à Maires :  
Très violent combat d’artillerie toute la nuit dans la région de Lorette et la sucrerie de Souchez. L’ennemi a prononcé à 21 heures une attaque qui a été aussitôt repoussée. Les allemands ont bombardé Neville-Saint-Vaast mais n’ont pas tenté de le reprendre. Nous avons réalisé de nouveaux progrès dans le labyrinthe. Dans la région d’Hébuterne notre gain entièrement maintenu porte sur un front de 1800 mètres et une profondeur d’environ 1 kilomètre. Rien de nouveau sur le reste du front.

**11 juin 16h –** Toulouse – Préfet à Maires :  
Rien d’important à ajouter au communiqué d’hier soir si ce n’est de nouveaux progrès dans le labyrinthe où nous avons continué à refouler l’ennemi. Quelques progrès à l’est du labyrinthe où nous avons enlevé plusieurs boyaux aux allemands près de la grande route d’Arras à Lille. Dans la région d’Hébuterne élargissement de nos gains au nord et au sud du front d’attaque du 7 et la conquête de plusieurs tranchées où nous avons fait 100 prisonniers et pris deux mitrailleuses.

**12 juin 15h45 –** Toulouse – Préfet à Maires :  
Rien à ajouter au communiqué d’hier soir si ce n’est de nouveaux progrès de nos troupes dans la région du fond de Buval nord de Lorette et dans celle du labyrinthe. Un brouillard épais règne dans le secteur au nord d’Arras.

**13 juin –** Toulouse – Préfet à Maires :  
Pendant toute la nuit la canonnade n’a pas cessé dans la région au nord d’Arras. Nous nous sommes emparés de la station de la voie ferrée à Souchez. Dans la partie sud du labyrinthe lutte opiniâtre à coups de grenades. Malgré les efforts acharnés de l’ennemi nous avons maintenu tous nos gains des jours précédents. Sur le reste du front nuit calme.

**14 juin 15h –** Toulouse – Préfet à Maires :  
Rien d’important à ajouter au communiqué d’hier. Les troupes belges ont jeté un bataillon sur l’Yser au sud du pont du chemin de fer de Dixmude. Dans le secteur au nord d’Arras plusieurs actions d’infanterie se sont déroulées en fin de journée. L’une nous a rendus maître d’un ouvrage allemand au nord de Lorette, l’autre nous a fait perdre sous un violent bombardement une partie de la tranche conquise par nous dans l’après-midi au nord de la sucrerie de Souchez. Sur le reste du front rien à signaler.

**15 juin –** Toulouse – Préfet à Maires :  
Rien d’important à ajouter au communiqué d’hier soir. Une attaque ennemie dirigée contre les tranchées conquises par nous le 6 à Quennevières a été complètement repoussée. Une pièce allemande à longue portée a lancé deux projectiles sur compiègne. Aucune victime aucun dégât.

**16 juin 15h40 –** Préfet à Maires :  
Les troupes britanniques ont enlevé hier une ligne de tranchée à l’ouest de La Bassée. Rien à signaler sur le reste du front. Un avion allemand a été obligé d’attérrir dans nos lignes près de Noroy-sur-Ourq nord-est de La Ferté-Milon. Les aviateurs sont prisonniers.

**17 juin 15h20 –** Toulouse – Préfet à Maires :  
Dans les Vosges nos progrès au cours de la journée d’hier nous ont rendus entièrement maîtres de la ligne de hauteur qui domine la vallée de la Fecht au nord de Osnabrück et de Metzeral. Au sud nous avons également gagné du terrain entre les deux bras de la Haute Fecht et sur les hauteurs qui séparent celle de la Fecht / Lauch. Sur le reste du front rien à ajouter au communiqué d’hier.

**22 juin 15h –** Toulouse – Préfet à Maires :  
Dunkerque a été bombardée cette nuit par une pièce à longue porté (14 obus). Quelques personnes appartenant à la population civile ont été tuées. Les troupes belges se sont emparées au sud-ouest de Saint-Georges d’une tranchée allemande dont tous les défenseurs ont été tués ou faits prisonniers.

Dans le secteur au nord d’Arras au cours de la nuit l’ennemi après un bombardement d’une grande intensité a attaqué sur plusieurs points. Il a été complètement repoussé sauf au sud de Souchez où il a réussi à prendre pied dans un élément de tranchée. Dans la région du labyrinthe il a subi de lourdes pertes. Une contre-attaque allemande dirigée dans la soirée d’hier contre les positions que nous avions conquises à l’est de la ferme de Quennevrières a été enrayée par le feu de notre artillerie et de notre infanterie. L’ennemi a fait usage de bombes asphyxiantes. En Argonne près de la route Binarville- Vienne le Château situation inchangée. En Lorraine nous avons par une nouvelle attaque élargie de trois-cents mètres vers le nord nos positions sur la crête est de Reillon, occupé les groupes au sud de Le Remabois, repoussé facilement une contre-attaque partant de Leintrey, une autre au sud-est de Parroy et fait des prisonniers. Dans la vallée de La Fecht tous nos gains sont maintenus et nous continuons à progresser. Nous avons dépassé Metzeral par le nord et par le sud et gagné du terrain au delà de l’Anlass Wassen. Dans la région de Sondernach nous avons fait des prisonniers et pris des mitrailleuses.

**23 juin –** Toulouse – Préfet à Maires :  
Dans la région au nord d’Arras le bombardement s’est poursuivi de part et d’autre pendant toute la nuit. Les allemands ont tenté deux nouvelles contre-attaque près du labyrinthe, l’autre près du cimetière de Neville. Elles ont été toutes deux repoussées. À l’ouest de l’Argonne près de la route de Binarville la lutte se poursuit depuis hier à coup de grenades. Sur le reste du front de l’Argonne les allemands ont fait une grande consommation de munitions mais sans prononcer aucune attaque d’Infanterie. Sur le Haut de Meuse à la Tranchée de Calonne nous avons en fin de journée reconquis une nouvelle partie de la seconde ligne allemande. En Lorraine de nouvelles contre-attaques contre nos positions ouest ont été repoussées. Nous avons maintenu tous nos gains en faisant des prisonniers. Dans les Vosges à La Fontenelle l’ennemi dans la soirée après avoir en quelques heures lancé quatre mille obus sur nos ouvrages avancés de 200 mètres a réussi à prendre pied. Il a attaqué en même temps les tranchées voisines. L’offensive a été enrayée par une défensive brillamment menée. Nous avons repris presque entièrement le terrain perdu. L’ennemi n’a réussi à se maintenir qu’à l’extrémité de l’ouvrage. Nous avons fait 140 prisonniers dont trois officiers. Dans la région de la Fecht nous avons occupé Sandernarch et nous avons poussé nos lignes à l’est du village.

**24 juin 15h20 –** Toulouse – Préfet à Maires :  
Dans la région au nord d’Arras la nuit a été relativement calme si ce n’est au nord de Souchez où la canonnade n’a pas cessé. L’ennemi a bombardé Arras. L’ambulance du Saint-Sacrement a été particulièrement éprouvée. Les religieuses et les infirmières ont été tuées. Devant Dompierre à l’ouest de Peronne l’explosion d’un fourneau de mine allemande a été suivi d’un violent bombardement de nos tranchées. Une tentative d’attaque de l’ennemi exécutée par un très faible effectif a été enrayée. Sur les Hauts de Meuse à la tranchée de Calonne situation inchangée. Nous nous maintenons dans une partie de la deuxième ligne allemande. En Lorraine près de Leintrey l’ennemi a attaqué. Après une lutte assez vive il a été repoussé. Sur le reste du front nuit calme. Le nombre de prisonniers faits depuis le 14 juin dans la vallée de la Fecht s’élève à 25 officiers, 53 sous-officiers et 638 hommes.

**25 juin 15h15 –** Toulouse – Préfet à Maires :  
Dans la région au nord d’Arras pendant la nuit nous avons attaqué entre Angres et Souchez etréalisé de nouveaux progrès. Au labyrinthe une contre-attaque allemande a été repoussée. Elle a été suivie par un violent bombardement de nos tranchées auquel nos batteries ont riposté. En Champagne près de Perthe et dans la région de Perthes l’ennemi dans la journée d’hier et pendant la nuit a fait exploser deux fourneaux de mines mais sans prononcer d’attaque d’Infanterie. Il n’a même pu récupérer les entonnoirs placés sous le feu de nos tranchées. En Argonne et à Vauquois la lutte de mines se poursuit et a donné lieu à des actions toutes locales à coup de bombes et grenades. Sur les Hauts de Meuse à la Tranchée de Calonne les allemands ont dans la soirée lancé sur tout notre front une attaque de grande violence accompagnée de bombes asphyxiantes et de liquides enflammés et après avoir réussi à pénétrer dans la partie de leur ancienne deuxième ligne que nous occupons ils ont été rejeté par une contre-attaque énergique de notre part. À minuit l’ennemi a tenté un nouveau retour offensif. Les assaillants ont été dispersés avec de lourdes pertes. En Lorraine l’ennemi a de même essayé par deux de reprendre les positions qu’il avait perdues près de Leintrey. Il a été complètement repoussé. Dans les Vosges deux attaques d’Infanterie allemande dirigées après un violent bombardement contre nos tranchées à Reichackerkopf ont été arrêtés par le feu d’artillerie et d’infanterie. Un avion allemand a lancé hier sans causer aucun dégât cinq bombes sur un sanatorium.

**28 juin 15h45 –** Toulouse – Préfet à Maires :  
Rien d’important à signaler au cours de la nuit si ce n’est deux attaques allemandes une à la tranchée de Calonne, l’autre à la tranchée de Metzeral. Toutes deux ont été repoussées.

**29 juin 16h00 –** Toulouse – Préfet à Maires :  
Dans la région au nord d’Arras la canonnade s’est poursuivie. La nuit dernière au nord et au sud de Souchez ainsi qu’au nord de Neville une action d’infanterie nous a permis de progresser dans la région d’Angres à Ablain. En Argonne à Bagatelle lutte incessante à coups de torpilles et de grenades. Dans les Vosges une attaque allemande a réussi à rejeter momentanément nos avant-postes. Nous avons par une contre-attaque reconquis le terrain perdu. Sur le reste du front nuit calme.

**30 juin 15h50 –** Toulouse – Préfet à Maires :  
Dans la région au nord d’Arras la nuit a été marquée par une violente canonnade et quelques actions d’infanterie au nord du Château de Calmel. Nous avons légèrement progressé au sud du Cabaret rouge, une attaque allemande a été repoussée. Dans les Vosges les allemands ont tenté contre nos positions à l’est de Metzeral une nouvelle attaque qui a été repoussé.

**1er juillet 15h00 –** Toulouse – Préfet à Maires :  
Nuit calme dans la région du nord d’Arras et jusqu’en Champagne. L’attaque allemande en Argonne signalée hier a été particulièrement violente. Les parties engagées peuvent être évaluées à deux divisions. Cette attaque a été enrayée. Les allemands ont subi des pertes importantes.

**2 juillet 15h00 –** Toulouse – Préfet à Maires :  
La canonnade a été rude toute la nuit sur un grand nombre de points du front notamment dans la région Woesten nord-est d’Ypres, dans celle de Souchez et dans celle de Vermelles. Au nord de l’Aisne après un bombardement violent et continue, une attaque de grenadières ennemies s’est produite vers deux heures contre nos positions du chemin d’Ablain. À Angres au nord de la route de Béthune et a complètement échoué. Près de La Boisselle une de nos mines a détruit des travaux avancés de l’organisation ennemie. En Argonne la lutte a continué très violente toute la nuit. Une seule attaque ennemie a été tentée avec l’appui de gros lance-bombes et de bombes asphyxiantes. Elle a été repoussée. Au quart en réserve dans le Bois le Prêtre on signale également une violente opération d’artillerie qui elle a été aussi repoussée par le feu de notre artillerie.

**3 juillet 15h00 –** Toulouse – Préfet à Maires :  
La lutte a continué toute la nuit en Argonne. Avec la même opiniâtreté nous avons maintenu nos positions et nous avons infligé à l’ennemi de très grosses pertes. Dans la région de Metzeral deux nouvelles attaques contre des positions des crêtes situées à l’ouest du village elles ont été repoussées. Sur toutes les parties du front canonnade très active et de tous les calibres. Des obus envoyés sur Arras ont déterminé quelques incendies dont on s’est rendu maîtres. Nos avions ont bombardé avec succès les gares de Challerange, (…)arren et Langemark ainsi que les batteries allemandes de Vimy et de Beaurains.

**4 juillet 15h00 –** Toulouse – Préfet à Maires :  
Dans la région au nord d’Arras l’ennemi a attaqué cette nuit en formation serrée nos formations du Chemin creux d’Angres à Ablain. Au nord de la route Aix-Noulette-Souchez les assaillants dispersés et repoussés par nos tirs de barrage et le feu de nos mitrailleuses ont subi de lourdes pertes. En Argonne la fusillade et la canonnade n’ont pas cessé de toute la nuit de la route de Binarville-Vienne-le-Château jusqu’au jour. De Paris on ne signale que quelques actions d’infanterie très localisées. Dans la région de La Fontaine aux Charmes pas de modifications de part et d’autre. Sur le front Haye les allemands après un très violent bombardement ont vers minuit prononcé une tentative d’attaque contre nos tranchées. Au nord de Regneville nos tirs de barrage n’ont pas permis aux troupes de déboucher devant Fey un bataillon parvenu devant nos fils de fer. Il a été obligé de se replier. Une nouvelle attaque exécutée du même point par un demi bataillon n’a pas eu plus de succès. Sur le reste du front rien à signaler.

**6 juillet 15h00 –** Toulouse – Préfet à Maires :  
La nuit a été moment(…) sur plusieurs points du front. En Belgique des troupes britanniques appuyées par notre artillerie se sont emparées de quelques tranchées allemandes au sud-ouest de Pelken sur la rive est du canal. Une lutte très vive s’est engagée autour de station de Souchez qui est restée entre nos mains malgré les efforts répétés de l’ennemi. La ville d’Arras a été bombardée toute la nuit. En Argonne combats incessants à coups de grenades et de pétards. Notre artillerie a déclenché à plusieurs reprises les fils de barrage qui ont interdit net leurs tentatives d’attaque. Les allemands ont attaqué par deux fois nos positions de la croupe sud du ravin de Sangoux. À l’est de la tranchée de Calonne ils ont été complètement repoussés. Dans la région du Bois le Prêtre les allemands ont repris l’offensive. Deux attaques dont l’une s’est étendue peu à peu de la partie (…)ale du bois jusqu’à (Souain), tandis que l’autre dirigée contre la partie (manque texte). Elles ont été toutes deux enrayées par notre feu d’artillerie et d’infanterie qui ont infligé à l’ennemi de très lourdes pertes.

**7 juillet 16h00 –** Toulouse – Préfet à Maires :  
Dans la régin au nord d’Arras le bombardement a continué toute la nuit. Deux attaques allemandes menées par de faibles effectifs contre la station de Souchez ont été repoussées. Sur les Haute de Meuse vers 21 heures une nouvelle attaque allemande contre nos positions contre la croupe sud du ravin de Sangoux a été arrêtée par nos fils de barrage. Les allemands ont attaqué en même temps à l’ouest de cette croupe où ils ont été également repoussés. Au sud-est de Saint Michel l’ennemi après un bombardement d’une extrême violence a pris cette nuit l’offensive sur un front s’étendant depuis la colline qui domine la rive droite de la Meuse au sud d’Ailly jusqu’à la Tête de vache. Dans la forêt d’Apremont sur un seul point dans La Vaux-Péry il a réussi à prendre pied dans notre première ligne sur un front d’environ 700 mètres. Partout ailleurs il a été repoussé avec de lourdes pertes. Dans la partie est du Bois le Prêtre nous avons enrayé une nouvelle tentative d’attaque allemande précédée de jets de liquides enflammés. Rien à signaler sur le reste du front.

**5 juillet -** Dardanelles :  
Les turc ont prononcé une attaque générale la plus importante depuis les premiers jours de mai pour nous jeter à la mer. À quatre heures un feu extrêmement violent d’artillerie s’est ouvert sur nos lignes et sur la zone arrière franco-anglaise. L’ennemi tenta ensuite plusieurs attaques d’infanterie mais aucune n’a pu arriver jusqu’à nos tranchées. Décimés par notre artillerie, fauchés par nos fusils et nos mitrailleuses les assaillants laissent pour la plupart sur le terrain. Pendant toute l’action les batteries ennemies de la Côte d’Asie tirèrent sans interruption et un cuirassé turc croisant entre Medoc et Chanac prit part à l’action. À plusieurs reprises des avions ennemis bombardèrent nos lignes. À la fin de la journée une quinzaine d’avions allié survolèrent l’aérodrome turc de Chanac, jetèrent plusieurs bombes et atteignirent avec de gros obus un hangar.

**8 juillet 15h00 –** Toulouse – Préfet à Maires :  
Dans la région au nord d’Arras plusieurs actions d’infanterie assez violente se sont développées au cours de la soirée et de la nuit entre Angres et Souchez. Au nord de la route de Béthune à Arras une attaque allemande précédée d’un très fort bombardement a été complètement repoussée. Au nord de la station du Souchez nous avons prononcé une attaque qui nous a permis de nous rapprocher du village nous nous sommés emparés d’une ligne de tranchées allemande après en avoir exterminé tous les défenseurs à coup de grenades. Nous avons progressé au-delà, nous avons fait quelques prisonniers et pris un canon. Soissons a été bombardé. En Argonne la fusillade et la canonnade n’a pas cessé toute la nuit. Au levé du jour dans la région de Marie-Thérèse les allemands ont essayé de sortir de leurs tranchées, ils ont été repoussés. Entre Meuse et Moselle nuit très agitée. Entre forêt d’Apremont et Bois le Prêtre, bombardements, jets de bombes, quelques actions d’infanterie si ce n’est entre Fey-en-Haye et le Bois le Prêtre où deux attaques de l’ennemi ont été enrayées.

**9 juillet 15h00 –** Toulouse – Préfet à Maires :  
De la mer à l’Aisne on ne signale au cours de la nuit qu’une action assez vive d’artillerie autour de Souchez. Un bombardement lent mais continu d’Arras et une canonnade violente entre l’Oise et l’Aisne. Sur le plateau d’Auray en Champagne lutte de mines. En Argonne fusillade et canonnade mais sans actions d’infanterie. Entre Meuse et Moselle la nuit a été mouvementée entre Fey-en-Haye et Le Bois le Prêtre nous avons par un combat à la grenade reconquis environ 150 mètres de tranchées perdues le 4 juillet. À La Croix des Carmes l’ennemi a attaqué dans la soirée sur un front de 350 mètres après un bombardement de torpilles aériennes et de jets de liquides enflammés. Après avoir réussi à prendre pied dans notre organisation de première ligne les allemands ont été rejeté par une contre-attaque immédiate. Ils n’ont réussi à se maintenir que dans quelques éléments de notre tranchée la plus avancée. Dans les Vosges dans la région de Ban de Sapt à la Fontenelle nous avons remporté un succès marqué après avoir chassé l’ennemi de la partie de notre ancien ouvrage qu’il nous avait enlevés le 22 juin.Nous nous sommes emparés de toutes les organisations défensives au sud-est de La Fontanelle jusqu’à la route de Launois-Moyenmoutier nos gains représentent une avance totale de 700 mètres. Nous avons fait 19 prisonniers officiers dont un chef de bataillon, deux médecins, 767 hommes non blessés appartenant à 7 bataillons différents. Nos ambulances ont recueilli un officier et 32 soldats allemands blessés. Nous avons pris un canon de 37, deux mitrailleuses, plusieurs lance-bombes et des munitions en grande quantité. Depuis le lever du jour l’ennemi bombarde notamment des positions perdues.


---  
 
### 1916  

**30 août –** Toulouse – Préfet à Maires – Le gouvernement a décidé à l’occasion de l’intervention de la Roumanie que les monuments publics départementaux seraient pavoisés en son honneur. Je vous prie de vous conformer à ces instructions.


---  
 
### 1917  

**7 avril –** Toulouse – Préfet aux Maires du département :  
Vous prie de bien pavoiser les monuments publics de votre commune aux couleurs américaines en l’honneur de rentrée en guerre à nos cotés de la grande République des États-Unis. Veuillez inviter les habitants de votre commune à arborer le drapeau étoilé des nouveaux alliés à coté du drapeau tricolore. Le pavoisement durera trois jours.


---  
 
### 1918

**10 juillet 11h25 –** Toulouse – Préfet à Maires :  
La fête du 14 juillet devra avoir cette année comme l’année dernière un caractère exclusivement patriotique et commémoratif. Les monuments publics seront en conséquence pavoisés comme d’usage et les distributions de bienfaisance qui sont de tradition dans toutes les communes seront maintenues. Par contre devront être supprimées toutes les manifestations présentant un caractère de réjouissances publiques, illuminations et feux d’artifices.

**11 novembre -**  Toulouse – Préfet à Maires :  
Faites sonner les cloches à toute volée, faites pavoiser les édifices publics aux couleurs françaises et alliées, faites illuminer et que chacun sorte drapeaux et lampions pour l’Armistice du Droit et de la Civilisation.

**********************

La source exclusive de ces communiqués est un dossier de télégrammes des « Postes et télégraphes » conservé aux Archives Municipales de Deyme. Retranscrites sur des bordereaux « Télégramme », ou sur des feuilles de cahiers ou de papier à lettre lorsque le communiqué était trop long, les informations de la Préfecture étaient transmises à la Mairie via la cabine téléphonique du village tenue par Louis MONFRAIX qui en avait obtenu la gérance en novembre 1912. Dans les deux cas, le télégramme est revêtu d’un numéro, du nombre de mots, de la source de transmission et de la date. Tous ces élément minutieusement enregistrés et des textes écrits « Très lisiblement » comme le recommande le service concerné, représentent un document exceptionnel.  

