---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

<style>
body {
text-align: justify; font-size:12pt}
</style>

<br>  

## L’affaire des Monges 

#### Robert PINCE    

<br>

---  

**Un contrôle banal**

Le 2 janvier 1944, lendemain de jour férié, aux alentours de midi, un pâle soleil d’hiver peine à dissiper les brumes matinales. Sur la route nationale Toulouse-Carcassonne, entre Pompertuzat et Deyme, de nombreux riverains observent un contrôle conjoint de la gendarmerie et de la police, sans doute organisé pour rechercher  les « terroristes » dont les coups de mains sont de plus en plus audacieux.: le 7 octobre 1943, ces combattants de l’ombre ont enlevé en pleine ville Allard-Dubreuil, un collaborateur de la Gestapo. Le 23 octobre, ils ont exécuté le chef de la Police régionale de Toulouse, qui s’était fait remarquer à Lyon par sa répression impitoyable des activités de résistance contre l’occupant.

Tous les passants remarquent que le contrôle est effectué par deux groupes de militaires et policiers: un premier groupe de 3 hommes (deux gendarmes et un inspecteur de police) est manifestement aux ordres d’un deuxième groupe de commandement formé d’un capitaine et d’un gradé de la gendarmerie, accompagné d’un policier en civil. Les riverains observent ce contrôle avec curiosité, comme Germain Bessières (67 ans), qui passe sur la route nationale avec sa charrette et ses boeufs ou Madame Bessières (29 ans) qui l’observe depuis sa maison, à 200 mètres de là. Fédéric Hébra (24 ans) habitant à Deyme, Madame Sibra (31ans) habitant la ferme des Monges, Monsieur Gribaudo (71 ans) habitant la ferme Menjou, remarquent eux aussi ce contrôle routier. A 12 heures 30 environ, se présente un convoi de trois véhicules en provenance de Toulouse: deux voitures de tourisme (202 Peugeot et Traction Avant Citroën) qui encadrent une camionnette Peugeot DK5. Les représentants de l’ordre leur font signe de s’arrêter, ce que chacun des conducteurs du convoi s’empresse de faire.  

<br>


**Un convoi de la Gestapo**

Ce convoi, d’apparence banale, qui vient docilement de s’arrêter sur l’ordre des gendarmes, est en réalité d’une importance capitale pour les occupants allemands: La camionnette Peugeot, conduite par un certain Toniutti, contient les archives de la Gestapo toulousaine, mais aussi des bagages, des pneus et 200 litres d’essence. Au volant de la Citroën qui ferme la marche, se trouve le SS Wilhelm Messack, sa maîtresse Paulette Bordier et à l’arrière Emilio Alzugaraï, une  mitraillette chargée à ses pieds. Messack, installé à l’hôtel Capoul de Toulouse, trafique au marché noir, pille les biens des juifs et traque sans merci les résistants toulousains. Il possède à son service des agents locaux, français pour la plupart, mais aussi étrangers comme l’italien Toniutti ou le basque espagnol Alzugaraï. Mais Messack vient de quitter Toulouse pour être muté à Nice.  Sa « feuille de route »: Lutter contre la résistance italienne qui fleurit dans toute la plaine du Pô. Il se trouve donc au tout début de son voyage vers Nice, arrêté provisoirement par des gendarmes un peu trop zélés. Ceux-ci, il en est persuadé, vont s’empresser de laisser passer le convoi quand ils verront à qui ils ont affaire.  

<br>


**Le groupe Morhange**

Ce que la SS ne sait pas, c’est qu’il n’a pas affaire à un banal contrôle de gendarmerie, mais qu’il se trouve face à un groupe redoutable et parfaitement bien renseigné, le groupe Morhange. Au début de l’été 1943, Marcel Taillandier dit Morhange a créé une équipe spéciale de contre espionnage chargée de mener une lutte sans merci contre l’occupant et ses serviteurs.; ce groupe (82 agents officiels) a recruté dans les mouvements de résistance et parmi les policiers toulousains. Il a même réussi à infiltrer un de ses membres dans la Gestapo de Toulouse! C’est ainsi que Pierre Saint-Laurens est devenu, sur ordre de la Résistance, un agent de la Gestapo économique de Toulouse. Et c’est lui qui a informé Morhange du prochain départ de Messack pour Nice. Morhange a donc décidé de monter une opération audacieuse, destinée à enlever le SS et ses sbires, tout en récupérant les archives d la Gestapo.

<br>


**Un traquenard soigneusement planifié**

Pour y parvenir, Morhange n’a rien laissé au hasard. Il a choisi le carrefour des Monges pour faciliter la fuite de ses hommes par la chemin qui monte à Deyme, ce qui leur permettra, en roulant vers l’Ouest de rejoindre ses base du Gers.

Sur la route 113, il a placé un premier groupe formé d’un « policier », Adebaud (dit l’aigle), et de deux « gendarmes » coiffés de képis authentiques prêtés par la gendarmerie nationale: André Fontès et Henri Barrau.

Un peu plus loin, sur la route nationale, le deuxième groupe de commandement est formé d’un « policier » Mercier (dit le petit Marcel) et de deux « gendarmes », Pierre Rous et Bronislav Doradzinski (dit Bruno), un ancien des brigades internationales.

Sur le chemin qui monte à Deyme, trois voitures sont dissimulées. a leur bord, Combatalade, Morhange, le capitaine Pélissier et l’adjudant-chef Maurice Colette.

Enfin, dans le bois d’acacias, près de la ferme des Monges, quatre hommes sont parfaitement camouflés dont Laigneau (dit Cambronne), son adjoint Longin (dit Durand) et Louis Ramond. Ils sont chargés de couvrir l’opération et d’assurer le repli en cas d’imprévu.  

<br>


**Des circonstances imprévues**

Tout se passe d’abord comme attendu: le convoi de la Gestapo une fois immobilisé, Toniutti mis en joue par Doradzinski, lève les mains en l’air, surveillé par Mercier, qui, la main sur son pistolet, veille au grain. Cependant, le pilote de la voiture de tête,malgré sa situation inconfortable, reste sûr de lui: il affiche l’air décontracté de celui qui sait par avance que son patron va facilement mettre au pas ces maudits gendarmes français.

C’est alors que survient l’inattendu: Pierre Rous, le canon de sa mitraillette dans la saignée du bras gauche, les trois galons de son képi étincelant au soleil, se dirige au pas de parade vers la Traction Avant. Mais à son approche, tout se précipite: le SS Messack a-t-il remarqué que l’un des gendarmes portait une mitraillette anglaise Sten, l’arme favorite de la résistance? En tout cas, il vient de réaliser qu’il vient de tomber dans une ambuscade. Il porte alors vivement la main à la poche intérieure de son veston, cherchant son pistolet. Trop tard! Anticipant le geste, Fontès a déjà ouvert le feu avec son Smith et Wesson et Pierre Rous lâché deux courtes rafales de mitraillette, la première sur Messack, la deuxième sur le colonel Alzugaraï. Paulette Bordier est abattue par une rafale tirée à bout portant par Barrau, tandis que Doradzinsky règle son compte à Toniutti. En quelques instants, tous les occupants du convoi viennent de passer de vie à trépas. Seul Pierre Saint-Laurens, qui conduisait la deuxième voiture, est sauf et peut rejoindre ses camarades.  

<br>


**Un bilan positif**

Le groupe de Morhange se replia ensuite sans problèmes vers ses bases du Gers, après avoir récupéré la camionnette des archives et la serviette de Messack. Le commando avait laissé sur place le corps de Toniutti, ainsi que la Traction Avant de Messack et ses trois cadavres. Saint-Laurens se réfugia peu après au maquis de Quérigut. Les archives et la serviette de Messack se révélèrent fort intéressantes puisqu’elles fournissaient un organigramme très complet de la Gestapo de Toulouse, ainsi que la liste des Français, Italiens ou Espagnols travaillant pour les allemands; enfin, des listes de dénonciateurs fort nombreux furent récupérées. Tous ces documents furent transmis aux service spéciaux de contre-espionnage d’Alger, sous les ordres du colonel Paillole.

Abasourdi par l’audace de l’opération, le SD (Sicherheitsdienst, « service de la sécurité ») allemand misa sur la capture probable de Saint-Laurens, promise par ses agents et informateurs. Pourtant, le « traître Saint-Laurens ne fut jamais arrêté. Morhange n’eut pas cette chance: il continua la lutte armée à la tête de son groupe, avant de tomber sous les balles allemandes le 11 juillet 1942. Cinq mois seulement après l’arrestation de Robert Desnos qui avait écrit dès 1942 ces vers prémonitoires:

*Après le dur travail clandestin*  

*Imprimeurs, porteurs de bombes, déboulonneurs de rails, incendiaires,*  

*Distributeurs de tracts, contrebandiers, porteurs de messages,*  

*Je vous salue, vous qui résistez, enfants de vingt ans au sourire de source*  

*Vieillards plus chenus que les ponts, hommes robustes, images des saison,*  

*Je vous salue au seuil du nouveau matin*  


**Robert DESNOS**, "*Le veilleur du Pont-au-Change*" (1942)

<br>


**Remerciements:**

Cet article a été largement inspiré par le remarquable article « Résistance contre Gestapo » paru en 2003 dans le numéro 57 de la revue « Couleur Lauragais » et signé Jean Odol. Nous tenons à l’en remercier.

De nombreux détails de l’affaire des Monges nous ont aussi été communiqués par Jean-Jacques Mazelier, fils d’un couple célèbre de résistants toulousains, Elise et Roger Mazelier. Qu’il en soit également remercié. 

