---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

<style>
body {
text-align: justify; font-size:12pt}
</style>

## Les cathares, qu’es aco?…
#### Bernard Thourel

**Catharisme**. Qui n’a pas vu sur nos routes de France un panneau annonçant : Vous entrez en pays Cathare. Ceci montre, s’il en est besoin, que le Catharisme fait partie de l’histoire de notre région.  

Il fait son apparition essentiellement dans les comtés de Toulouse, Albi, Carcassonne, Béziers et toute la Septimanie.  

Il n’est pas question ici d’entrer dans les détails de la doctrine, mais disons simplement qu’elle niait l’existence de Dieu et prônait une éthique de vie que l’église catholique ne pouvait tolérer.  

Il faut remarquer cependant que le catharisme est un symbole de la tolérance, de la liberté et de l’ouverture d’esprit de la culture occitane.  

Quoi qu’il en soit, l’église désigne les cathares comme hérétiques (Il faut noter ici que cette hérésie a été largement instrumentalisée par Raymond IV alors comte de Toulouse et ceci à des fins politiques). Le premier travail de l’église a été d’envoyer des prédicateurs pour éradiquer cette hérésie. Elle les a trouvé divers ordres religieux : les cisterciens, les franciscains et les dominicains. Malheureusement, ce fut un échec. Les plus connus de ces prédicateurs sont St Bernard et St Dominique.  

Devant cet état de fait, le pape Innocent III lance, en 1208, Une première croisade contre les Cathares. Avec cette première croisade dite ˝contre les Albigeois˝, il s’agit pour l’église de mater une hérésie mais, en plus, pour la couronne de France, de soumettre les vassaux du sud un peu trop indépendants et d’une richesse enviable. Philippe Auguste, alors roi de France, ne voudra jamais participer à cette croisade, mais laissera ses vassaux libres de toutes actions. La guerre durera vingt ans (1209-1229). Á la tête des croisés se trouvent : Eude III duc de Bourgogne, le Comte de Nevers et le Comte de Saint Pol. Ce n’est qu’après la prise de Carcassonne que Simon IV de Montfort deviendra le le chef de la croisade, les trois précédents décidant de rentrer sur leurs terres. Le légat Arnaud Amaury (moine cistercien) donne alors à Simon IV de Montfort, les terres de Trencavel et le titre de Vicomte de Carcassonne.
Sur le plan spirituel, l’armée est relayée par l’Inquisition, qui n’hésite pas à faire appel à l’ordalie. Ainsi, tous les ˝Parfaits˝ (en quelque sorte le clergé des Cathares) ayant été éliminés, les mourants ne pouvaient plus recevoir l’absolution (consolamentum), cette dernière ne pouvant être donnée que par un ˝Parfait˝.  

L’Inquisition faisant ainsi disparaître le clergé cathare, en a ainsi fait disparaître le culte.  

### Saint Dominique à Deyme   

Saint Dominique, de son vrai nom Dominique de Guzmàn, est né à Caleruega, province de Burgos. Lors de ses nombreux voyages, il rencontre en Occitanie l’hérésie cathare qu’il essayera en vain de combattre par la parole. En 1215, il s’établit à Toulouse d’où il fondera un ordre prêcheur : les Dominicains. Á l’époque, Simon IV de Montfort extermine par le fer et le feu le maximum de cathares.  

Bien qu’en étant en opposition avec cette hérésie, il ne prendra jamais part aux combats. Il voue une véritable dévotion au Rosaire, cette dévotion ayant été répandue par son disciple Alain de la Roche.
Notre église a dans son patrimoine un très beau tableau (dernièrement restauré) représentant la remise du Rosaire à Saint Dominique.  

### Le sac de Béziers   

L’armée des croisés, forte de 20.000 hommes, se présente devant Béziers ville fortifiée. Renaud de Montpeyroux, évêque de Béziers, tente une médiation. Le légat Arnaud Amaury exige que tous les Cathares lui soient livrés. L’évêque dresse une liste de 220 noms d’hérétiques (Sur quels critères, on ne sait). L’évêque fait alors remarquer les difficultés morales et matérielles pour une telle entreprise. L’abbé de Cîteaux exigea alors que tous les catholiques sortent de la ville pour ne pas partager le sort qui est réservé aux hérétiques. Mais la population et les consuls (les capitouls) repoussent cette exigence, restant solidaires de leurs concitoyens.  

L’armée atteint la ville le 22 juillet 1209. Béziers est alors fortifiée et le siège mis en place risque d’être long. Ce jour-là est très chaud et quelques soldats vont se rafraîchir dans l’Orb. Ce que voyant, des biterrois tentent une sorte pour en découdre. Las! L’affrontement tourne mal et les biterrois refluent en désordre dans leur ville, poursuivis par la soldatesque. Totalement submergés, les biterrois sont incapables d’empêcher l’envahissement de leur cité et le massacre commence : on ne respecte même pas ceux qui se sont réfugiés dans les églises ! La ville est alors mise à feu et à sang. Rien ni personne ne peut être sauvé ! 

Les chroniqueurs parlent de 15000 à 20000 personnes massacrées. C’est sans doute un peu exagéré car la population de la ville n’excédait pas 14000 âmes. On parle ˝simplement˝ de 7000 personnes massacrées dans la seule église Sainte Madeleine.
La prise-éclair et le massacre font l’effet d’un vrai coup de tonnerre dans toute la France et la nouvelle se répand hors du pays tant Béziers passait pour une ville très fortifiée et on ne pouvait pas penser qu’elle ne tiendrait pas longtemps.  

Le massacre de Béziers est aujourd’hui entré dans la mémoire locale (lou grand masé).
Enfin, citons cette phrase mémorable qui aurait été prononcée par Arnaud Amaury : ˝Massacrez-les, car le Seigneur connaît les siens˝, phrase déformée et attribuée à Simon de Montfort : ˝Tuez-les tous, Dieu reconnaîtra les siens˝ (?).  

### La chute de Montségur   

Perché sur un piton rocheux, le château de Montségur semblait imprenable (d’où son nom). Il fait partie d’une lignée de châteaux dits ˝cathares˝. On peut signaler les suivants : Puységur, Peyrepertuze, Quéribus etc. Tous ces châteaux étaient situés dans des lieux stratégiques et puissamment défendus.  

Une paix ayant été signée en 1243 entre le roi de France et le Comte de Toulouse, il a fallu mettre fin à l’Occitanie indépendante et au catharisme. Montségur représentait alors le refus de l’autorité royale et papale.  

Dans ses flancs s’étaient réfugiés 400 croyants cathares. Ils se sentaient en sécurité devant les assiégeants. Ce défi à l’autorité du roi et du pape dura un an. Le nombre des assiégeants était de 10000. Les boulets et autres catapultes n’avaient aucun effet sur les murs.
Ces assiégeants, aidés par des montagnards habitués à l’escalade et connaissant le pays, réussissent, par surprise, à entrer dans la place et obtinrent sa capitulation complète.
Le 1er mars 1244, Pierre-Roger de Mirepoix est contraint de négocier avec les cathares. Les termes en furent les suivants :  

	La vie des soldats et des laïcs sera épargnée  
	Les Parfaits qui renieront leur foi seront épargnés  
	Une trêve de 15 jours est accordée aux cathares qui voudront se préparer et recevoir leur dernier sacrement.  

Le 16 mars, la forteresse s’ouvre : le bûcher est prêt ! 220 cathares se jettent volontairement dans les flammes, refusant d’abjurer : hommes, femmes, enfants. Il furent suivis par des soldats qui n’avaient pas voulu les abandonner. On dit que certains chantaient.
Une stèle a été érigée. Elle porte l’inscription suivante : ˝Als catars, als martirs del pur amor crestian, 16 de març 1244˝.  

En souvenir de ce bûcher, son emplacement porte ce nom: ˝Lou Camp dels Cremats˝.
Ces événements signent la fin de l’Occitane indépendante.  
 
Deyme, 18 novembre 2015

