---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

<style>
body {
text-align: justify; font-size:12pt}
</style>

## Mathilde, une amie belge réfugiée      
#### Christian Balland      

Au numéro 7 de la rue du Crucifix vivait une famille dont le dernier membre à occuper les lieux a disparu en 2003. Siège d’une entreprise de transports, d’une entreprise agricole, cabine téléphonique et enfin maison paisible, ce lieu dégageait dans mon enfance un air permanent de magie. Cet état tenait à la personnalité de sa propriétaire, ma tante et marraine, à qui je dois de merveilleux moments pour être né dans ses murs et avoir été considéré comme un fils. La situation m’a fait bénéficier de son sens inné de la décoration, appliquée tant à l’intérieur que dans un jardin qui sentait bon la fantaisie et la liberté. Mais le plus grand des bénéfices est sans doute la narration de certains événements: un incendie traumatisant, une enfance passée au pied d’une caserne de « fiers dragons », sa rencontre avec mon oncle, leurs débuts laborieux et une incroyable somme d’anecdotes liées à la personnalité des êtres qui lui étaient chers.

Ainsi, dans cette mémoire bien ordonnée vivait Mathilde, venue de Belgique en des temps troubles. Son nom de famille m’a toujours été inconnu, mais qu’importe, je retiens des récits l’histoire d’une amitié dont l’évocation illuminait les visages.

D’autres maisons alentour ont accueilli des compatriotes de Mathilde et des arrivants d’horizons divers durant l’exode débuté en mai 1940: rue de la Croix de Talou, aux châteaux du Major, de Bellevue et de Trébons et ce jusqu’à loger au total 131 personnes les mois suivants de juin et de juillet sur tout le territoire communal. Un état descriptif des immeubles susceptibles de recevoir des réfugiés était dressé à fin de réquisition. Il indiquait en outre leur situation géographique, le nombre de pièces, de lits et les détails favorables à un relatif confort. Une fiche établie par l’Ingénieur Vicinal de Villefranche-de-Lauragais (Haute-Garonne) en donne un aperçu: « Situé à 2,500 km environ du village et de la RN 113. Approvisionnement à domicile, route d’accès en très bon état. Comprend: au rez-de-chaussée une très grande cuisine. Salle à manger et salon à l’étage. 8 chambres contenant 8 lits de deux personnes. Appartement entièrement meublé et en bon état. Mobilier ancien. Nombre de personnes logées avec meubles existants: 15. Il serait possible de loger en plus une famille de 10 personnes. Electricité: Installation intérieure en bon état. Á prévoir un branchement extérieur. Une cuisinière« . Ce même logement comportait « un local complémentaire pouvant recevoir 25 personnes supplémentaires« . Une autre grande demeure pouvait accueillir jusqu’à 35 personnes.

Pour des temps d’occupation de 15, 31, 46, 61 et 91 jours, les propriétaires percevaient une indemnité de logement de 0,50 franc par jour et par personne, plus 0,25 franc pour l’éclairage et 0,25 franc pour le chauffage. Les sommes correspondantes étaient versées par la perception de Montgiscard. Sous l’autorité du Maire, la répartition de ces indemnités, la répartition des allocations à payer aux réfugiés, les allocations payées par nationalités et la difficile conciliation des causes communes incombaient aux délégués aux réfugiés, dont certains se mettaient spontanément au service de l’administration communale. La population aidait au mieux : « Grâce à une personne aimable, 6 personnes ont pu dormir dans des lits, les draps et les couvertures étant fournis« . Il en résultait un climat général dont témoigne ce courrier de la Direction du Service des Réfugiés adressé au Maire de Deyme: « Il n’a été commis aucun dégât par les occupants. Madame P. atteste qu’ils se sont comportés d’une façon irréprochable. »

Le jour de son départ, Mathilde a remis dans sa valise « l’Escaut, les cathédrales et les chemins de pluie » chantés plus tard par un grand « pays ». Mais tant de choses sont restées… En écoutant bien, on perçoit encore aux abords de la maison les entrelacs musicaux des accents réunis dans un nuage diffus, tantôt noir de regrets, jaune comme l’éclat d’un sourire ou teinté du rouge intense des coquelicots de nos prairies…

 

 

Deyme 28 novembre 2015
