---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

<style>
body {
text-align: justify; font-size:12pt}
</style>

## Statistiques agricoles  
#### Christian Balland  

---  

#### Production céréalière moyenne fin XVIIIe siècle

| Céréales |Avant 1782 | 1782|  
|:-----------------|:------------:|:-----------:|  
|Blé / Froment | 2000 | 2305 |  
|Orge |	100 |	50 |  
|Avoine |	100 | 50 |  
|Millet & Légumes | 2100 |	1300 |  
|Foins & Fourrages | 200 | |  
|Paille | | 250 |  

---

#### Répartition des 7O5 hectares du territoire communal en 1885  

 + Prairies →	142,49 ha  
 + Cultures → industrielles	208,24 ha  
 + Céréales → 120,35 ha 
 + Vignes →	42,87 ha  
 + Jachères →	100,63 ha  
 + Prairies naturelles → 46,75 ha  
 + Bois et forêts →	16,12 ha  
 + Jardins des particuliers →	5,48 ha  
 + Landes-pâtis-bruyères → 16,57 ha  
 + Terrains marécageux → 2,1 ha  
 + Terrains bâtis et non bâtis → 3,45 ha
 

---

#### Superficie des terres cultivées en ha de 1900 à 1950:

 + Superficie de la commune 705 ha  
 + Moyenne des terres labourables de 530 à 600 ha  
 
|Année | Blé | Avoine | Maïs | Vigne | P. d terre | Fèves | Haricots |  
|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|  
|**1900** | 195 | 12 | 97 | 6 | 8 | 12 | 8 |  
|**1902** |	195 | 8 | 100 | 15 | 4 | 12 | 4 |  
|**1903** |	200 |	10 | 100 | 15 | 4 | 10 | 5 |  
|**1904** | 190 |	15 | 110 | 17 | 5 | 12 | 6 |  
|**1905** | 180 | 20 | 115 | 17 | 7 | 10 | 6 |  
|**1906** |	170 |	25 | 120 | 19 | 6 | 10 | 8 |  
|**1907** | 180 |	20 | 125 | 13 | 6 | 8 | 10 |  
|**1908** | 190 |	20 | 115 | 14 | 7 | 10 | 8 |  
|**1909** | 185 |	25 | 120 | 14 | 8 | 12 | 6 |  
|**1910** | 180 |	20 | 80 | 16 | 7 | 10 | 7 |  
|**1911** | 190 |	25 | 95 | 18 | 7 | 10 | 6 |  
|**1912** | 185 |	20 | 90 | 18 | 6 | 10 |6 |  
|**1913** | 190 |	25 | 95 | 19 | 8 | | 6 |  
|**1914** | 175 |	10 | 83 | 18 | 6 | 4 | 5 |  
|**1915** | 118 |	15 | 65 | 18 | 4 | 2 | 3 |  
|**1916** | 105 |	10 | 60 | 18 | 4 | 2 | 2 |  
|**1917** | 95 |	12 | 40 | 18 | 4 | 2 | 2 |  
|**1918** | 128 |	20 | 47 | | 3 | 3 | 3 |  
|**1919** | 125 |	15 | 40 | 18 | 4 | 2 | 3 |  
|**1926** | 115 |	15 | 40 | 18 | 4 | 2 | 3 |  
|**1929** | 189 |	53 | 61 | 18 | 9 | 12 | 8 |  
|**1930** | 120 |	53 | 40 | 18 | 5 | | 3|  
|**1932** | 125 |	53 | 35 | 19 | 5 | 3 | 3 |  
|**1942** | 154 |	24 | 48 | 19,5 | 6 | 5,6 | 6,2 |  
|**1950** | 150 |	30 | 55 | 23,8 | 5,25 |	7,65 | 8 |  


---

#### Production céréalière pendant la Première Guerre Mondiale en hectolitres

|Céréales | 1915 | 1916 | 1917 | 1918 |  
|:--------------:|:----------:|:----------:|:----------:|:----------:|  
|**Blé** | 1140 | 2035 | 1916 | 2385 |  
|**Avoine** | 223 | 426 | 344 | 693 |  
|**Orge** |	7 | 61 | 140 | 130 |  

 
---

#### Rendement moyen du blé et de l’avoine 1900-1930

|Années | | Blé | | | | Avoine | |  
|:----------:|:-----:|:-----:|:---:|:---:|:---:|:-----:|:-----:|  
| | **Quintaux** | | **Hectare** | |**Quintaux** | | **Hectare** |  
|**1900** | 195 | | 10,35 | |  12 | | 6,25 |  
|**1903** | 200 | | 13 | | 10 | | 11 |  
|**1914** | 175 | | 9 | | 10 | | 10 |  
|**1919** | 125 | | 10 | | 15 | | 15 |  
|**1921** | 115 | | 9 |  
|**1926** | 120 | | 14 | | 54 | | 11,5 |  
|**1928** | 120 | | 11 | | 53 | | 10 |  
|**1929** | 189 | | 16 | | 53 | | 20 |  
|**1930** | 120 | | 5 | | 53 | | 5 |  


---

#### Animaux de ferme 1900-1951

|Années |Boeufs |	Vaches | Chevaux | Brebis | Porcins | 
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|  
|**1900**| 80 | 6 | 26 | 100 | 40 |  
|**1905**| 82 | 8 | 24 | 103 | 86 |  
|**1914**| 70 | 10 | 11 | 40 | 55 |  
|**1915**| 64 | 10 | 8 | 30 | 30 |  
|**1916**| 60 | 10 | 8 | 35 | 26 |  
|**1917**| 60 | 10 | 8 | 30 | 26 |  
|**1918**| 86 | 9 | 13 | | 11 |  
|**1921**| 80 | 8 | 13 | | 22 |  
|**1927**| 98 | 10 | 7 | | 57 |  
|**1942**| 97 | 48 | 7 | | 115 |  
|**1949**| 94 | 66 | 75 | | 141 |  
|**1951**| 88 | 63 | 5 | | 72 |  
 