---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

<style>
body {
text-align: justify; font-size:12pt}
</style>

<br>  


## Un italien en terre lauragaise


#### Victor VIDOTTO  

<br>

---  

Ma famille doit à la sagesse de ma mère d’avoir connu la France et d’y avoir vécu.  

<br>

En Italie, nous étions chez nous, dans une petite maison, mais mon père, qui avait connu la guerre et par deux fois était monté au front, souffrait du manque de travail et de ne pas élever les siens dans de meilleures conditions que par des emplois précaires épuisants. Scieur de long de traverses de chemin de fer était l’un d’eux. Las de vivre péniblement, après une demande à Gènes auprès des autorités, il fut embauché comme manœuvre sur le bateau qui l’emmenait en Amérique où il y avait beaucoup de travail, surtout dans les chambres frigorifiques. Au bout d’un an et demi, ma mère le fit revenir en lui disant qu’en France il pouvait travailler et réunir la famille. Il s’y rendit directement et, après avoir obtenu un contrat dans le Gers, revint en Italie nous chercher.

Mes parents, mes quatre soeurs et moi (je suis l’aîné) avons quitté l’Italie le 24 octobre 1925 au soir pour arriver à la gare d’Auch le lendemain 25 octobre vers midi. A notre arrivée, le propriétaire nous a fait déjeuner, mais déjà, un travail nous attendait. Il avait acheté une paire de vaches que mon père était chargé d’aller récupérer l’après-midi dans une propriété distante d’environ quinze kilomètres. L’aller se fit en voiture. Vers 16h30 après les présentations et l’évocation du passé et de notre voyage, nous sommes allés chercher les bêtes au pacage et les avons enfermées dans l’étable. Puis, le patron exigea un essai. avec joug et charrue.

Vers 19h30, nous étions encore sur place et la nuit était tombée. L’idée de voyager dans le noir sur des routes inconnues m’inquiétait, j’avais quatorze ans… Les vaches n’étaient pas jointes et n’avaient même pas de cordes, totalement libres de leurs mouvements. Affables, elles suivaient comme deux agneaux, comme des chiens dressés. Leur ancien propriétaire nous avait donné des conseils tels que nous placer l’un devant, l’autre suivant l’équipage docile visiblement habitué.

Malgré toutes les précautions et peu de voitures à cette époque sur cette route d’Auch à Vic-Fezensac, l’une d’elles est venue heurter une bête qui n’a pas eu de mal, heureusement. Le chauffeur ne nous a pas vus, l’éclairage des véhicules était alors ce qu’on appelait un lampion.

Mis en retard par cet incident et un peu perdus, imaginez avec quel soulagement nous vîmes arriver le patron qui, inquiet, s’était mis à notre recherche. Une famille nous accueillit pour la nuit. Une assiette de soupe nous attendait et le repos bien mérité a suivi sans attendre. Quel bonheur ce fut de nous savoir tous à l’abri.

Le lendemain matin, nous avons joint les bêtes et pris le départ pour la ferme, accompagné en partie par le patron parti devant en voiture. Il nous avait fait préparer le repas. A notre arrivée, tout était prêt sur une table d’autrefois, comme en ont encore les anciens. Pour nous c’était bon… c’était bon!!

Immédiatement, nous avons exploité la propriété. La sécheresse n’a pas permis les labours immédiatement, et en attendant, nous avons commencé à nettoyer les bordures des champs de la propriété de 15 à 18 hectares, commandés par mon père. Ce dernier faisait les gros travaux, mais savait difficilement mener une charrue.

Nous avons appris le travail de la terre avec nos voisins : comment tenir propres les vaches et les faire manger, selon les usages d’ici. Avec ma mère, nous nous sommes beaucoup occupés de la ferme. Nous déménagions presque chaque année et après Auch, nous sommes allés près de Vic-Fezansac (Gers) où nous sommes restés trois ans comme maîtres-valets, puis à Carcassonne (Aude) deux ou trois ans, vers 1939. Mais mon père ne trouvait pas son bonheur dans cette nouvelle vie de travailleur de la terre et s’adaptait  malgré son principe:  « La goccia que continua rompa la cesa. »

Ma soeur et moi nous sommes mariés la même année et quand nous le lui avons annoncé, mon père a décidé de rentrer en Italie. Il est parti en mars, nous nous sommes mariés en juillet. Un an et demi après, il a voulu revenir en France et nous avons travaillé sur une propriété que j’avais en fermage à Trébons-sur-la-Grasse (Haute-Garonne, canton de Revel). Nous n’y sommes restés qu’un an et de là, nous sommes partis à Mongeard (Haute-Garonne, canton d’Escalquens). Le propriétaire m’a tout donné: le grain pour ensemencer, une vache pour labourer et la confiance. Nous, n’avions rien d’autre qu’un fils et de la volonté. Nous faisions notre beurre et notre fromage. J’ai plus tard acquis une vache qui me donnait dix à douze litres de lait par jour. Cette vache m’a fait un mâle. L’autre aussi, ce qui m’a permis plus tard d’avoir une bonne paire de boeufs. C’est ainsi que j’ai vraiment commencé ma vie de paysan. J’ai quitté Montgeard en 1944 pour chercher une propriété mieux équipée en matériel. Nous l’avons trouvée à Bélesta-en-Lauragais (Haute-Garonne, canton de Revel), avec lieuse et semoir… cela m’aidait beaucoup. Nous y sommes restés en métayage jusqu’en 1948.

Puis Ségreville (Haute-Garonne, canton de Caraman) pendant neuf ans.

Enfin, nous avons trouvé une bonne petite propriété à Aurin (Haute-Garonne, canton de Lanta) où nous nous sommes fixés dix-neuf ans en fermage, jusqu’à la retraite en 1976.

J’avais acheté à Deyme en 1971, où je me suis retiré avec mon épouse Angèle, soutien indéfectible pendant ces longues et dures années que l’on se prend à regretter pour avoir connu le bonheur des gens à qui on laisse une chance  de montrer sa valeur… par l’effort!


<br> 

<div style= "float:right;position: relative;margin-left: 20px"> 
Deyme, Octobre 19845  
</div>

